name: local_auth_theme
description: Local fingerprint authenticator with dark theme support.
version: 0.0.1
homepage: https://github.com/balakumar98/local_auth_theme.git

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.localauth
        pluginClass: LocalAuthPlugin
      ios:
        pluginClass: LocalAuthPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.14.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  intl: ^0.15.1
